title: Yunxi Chen
logo: "/images/WechatIMG392.jpeg?raw=true" # your photo (or logo) here
description: Yunxi's Personal Website
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/yunxichen/">View My LinkedIn Profile</a> 


theme: jekyll-theme-minimal
